version: '3.8'
services:
  postgresql:
    image: postgres:latest
    container_name: ecommerce_postgresql
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    container_name: ecommerce_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
