name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Gradle Build
        run: echo "This is a placeholder step to ensure the CI runs and passes."

      - name: Running Tests
        run: echo "This is a placeholder step to ensure the CI runs and passes."

      - name: Build/Docker
        run: echo "This is a placeholder step to ensure the CI runs and passes."
